title: G Junk Yard
author: JPGabarre
email: juanplluisgabarre@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Explicacio del que faré com a projecte del treball final
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /projecteDAW
texture:
  title: G Junk Yard
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    github:  JPGabarre
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
